# Generated by Django 5.0.2 on 2024-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('option', models.CharField(choices=[('Icecream', 'Option 1'), ('Cones', 'Option 2'), ('Familypack', 'Option 3')], default='Icecream', max_length=20)),
                ('quantity', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
